### ISSUE TITLE
bybit does not have market symbol errors

### ISSUE THREAD

**Issue by Pusherman2** [Imminent-Darkness/BCDTB#1]
Hi there, 

Cool project! I am getting the following error when running however:

```
bybit fetch_ticker failed due to exchange error: bybit does not have market symbol USDT
bybit fetch_ticker failed due to exchange error: bybit does not have market symbol USDT
bybit fetch_ticker failed due to exchange error: bybit does not have market symbol USDT
bybit fetch_ticker failed due to exchange error: bybit does not have market symbol USDT
bybit fetch_ticker failed due to exchange error: bybit does not have market symbol USDT
Unable to fetch last ticker
```

This seems to happen regardless of specifying 'USDT', 'BTC/USDT' or in list format.

**Comment by Pusherman2** [comment]
Setting to BTCUSDT seems to work but getting the subsequent error:

`Fetching BTCUSDT time frame bars for 2023-02-21T21:10:40.970231...
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 3185, in ndim
    return a.ndim
AttributeError: 'tuple' object has no attribute 'ndim'

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.`

**Comment by Imminent-Darkness** [comment]
Hi,
I also had these issues when trying to run this outside of the Anaconda environment that I built it in. I think a specific version of either numpy or pandas is required and I was getting errors from pip when attempting to install all the right packages. I am going to try exporting the Anaconda environment into a python venv environment and include it in the repository. I'll comment back here when I get it done.

**Comment by Pusherman2** [comment]
Hi Imminent-Darkness,

Thank you for your reply. That makes sense if you built it with a specific environment. Please let me know when you have exported it with the correct python venv so I can activate it to run it without errors :)

Thank you and kind regards.

**Comment by Imminent-Darkness** [comment]
I'm having issues with finding a way to export my conda environment to a venv. You'll have to install Anaconda or maybe mini-conda for now. Pick python3.8 for your interpreter. I just pushed an environment.yml file to the repository. Inside a conda terminal run:

conda env create -f environment.yml

Activate the environment and run the script from there. 

Hopefully there's no issues. I'll keep trying to work out a better solution.

**Comment by Pusherman2** [comment]
Hi there,

Thank you for your efforts! I will deploy a test VM and install python 3.8, anaconda and deploy the environment there since all my machines are running python3.9+. Will let you know if I come up with any issues.

**Comment by Pusherman2** [comment]
Hi, will need to do some more testing. I had some issues while running on Win10VM using python 3.8 and Anaconda 2020.11. Had to go to Python 3.9 and latest Anaconda versions which seem to now atleast work together. Will let you know once I get the environment enabled and running and to run the bot :)

**Comment by Pusherman2** [comment]
Hi there,

I have managed to get it working using the conda env you provided, thank you. Trying to use the 'USDT' string for using all symbols is impossible however. Seems like it requires the following format: "BTCUSDT" rather than BTC/USDT. Setting to 'USDT' will not parse the m markets correctly. Changing to:
`m = m.replace("/USDT", "USDT")
 symbol = m
assets.append(myasset.Myasset(exchange,symbol, timeframe, amount, leverage, stoploss, takeprofit))`

Seems to remediate the issue. Setting the leverage on initial startup however does not work correctly as it still takes "USDT" as the symbol.

Whilst running, I am noticing however, that for certain symbols it is not generating charts/buy or sell signals. I am assuming it is because there is an error somewhere in the data collection from the API of these symbols but I don't see any errors in the console. 

Succesful:
`Fetching HOOKUSDT time frame bars for 2023-03-11T10:20:43.565906...
checking for buy and sell signals...
Checking if in micro uptrend...
changed to uptrend, buy if price is above wma
either the price is not above the weighted moving average
 or we are already in position`

Unsuccesful:
`Fetching LINKUSDT time frame bars for 2023-03-11T10:21:15.503180...
checking for buy and sell signals...
Directory C:\Users\User\Documents\BCDTB\charts\LINKUSDT-charts created successfully
done`

Any idea how to get signals/charts successfully for all symbols?

Also running on '1m' timeframe gives the following error on execution:
`Fetching BTCUSDT time frame bars for 2023-03-11T11:13:00.813340...
Traceback (most recent call last):
  File "C:\Users\User\Documents\BCDTB1m\bot.py", line 123, in <module>
    schedule.run_pending()
  File "C:\Users\User\anaconda3\lib\site-packages\schedule\__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "C:\Users\User\anaconda3\lib\site-packages\schedule\__init__.py", line 100, in run_pending
    self._run_job(job)
  File "C:\Users\User\anaconda3\lib\site-packages\schedule\__init__.py", line 172, in _run_job
    ret = job.run()
  File "C:\Users\User\anaconda3\lib\site-packages\schedule\__init__.py", line 661, in run
    ret = self.job_func()
  File "C:\Users\User\Documents\BCDTB1m\bot.py", line 116, in run_bot
    a.run_bot()
  File "C:\Users\User\Documents\BCDTB1m\python\myasset.py", line 875, in run_bot
    macroUP = self.df['50_ewm'][lastRow] > self.df['200_ewm'][lastRow]
  File "C:\Users\User\anaconda3\lib\site-packages\pandas\core\series.py", line 955, in __getitem__
    return self._values[key]
IndexError: index -1 is out of bounds for axis 0 with size 0`

Seems like the dataframe yields an empty result: 
Empty DataFrame
Columns: [Timestamp, Open, High, Low, Close, Volume, 50_ewm, 200_ewm]
Index: []

Cheers

**Comment by Imminent-Darkness** [comment]
I will definitely take a look at that when I get a chance. I had issues with reducing the Pandas DataFrame to 50 candles in the charting function. It was throwing errors and I didn't have the time to work on it, so I put it in a try/except block. If you want to look at it yourself, you can uncomment line 14 & 15 in bot.py and see if you can get any useful information from turning debugging on. I'll try to take a look at it soon.

**Comment by Pusherman2** [comment]
Hey there,

No worries, there is no rush :) I have actually written something similar to your algo in python for some practice. It is very barebones/boilerplate but in principle should do the same with less dependencies. Only thing is, is that ccxt is very poorly documented/buggy (in my opinion). I only had some troubles there. 

I will close this issue but keep an eye out for any updates/your projects.

Thank you and kind regards.
